show databases;

drop database storeFront;

create database storeFront;

use storeFront;

create table users (id varchar(30) NOT NULL, first_name VARCHAR(50) NOT NULL , last_name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) ;

create table addresses (ID VARCHAR(30) NOT NULL ,user_id VARCHAR(30) NOT NULL , ADDRESS VARCHAR(100) NOT NULL ,PRIMARY KEY(id), FOREIGN KEY(USER_ID) REFERENCES USERS(ID));

create table PRODUCTS (id varchar(30) NOT NULL, name VARCHAR(50) NOT NULL , QUANTITY INT(5) NOT NULL, PRIMARY KEY(id)) ;

create table PRODUCT_IMAGES ( PRODUCT_ID VARCHAR(30) NOT NULL , IMAGE TEXT NOT NULL , FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID));

create table CATEGORIES ( PRODUCT_ID VARCHAR(30) NOT NULL , CATEGORY VARCHAR(100) NOT NULL , FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID));

CREATE TABLE ORDERS ( ID VARCHAR(30) NOT NULL, USER_ID VARCHAR(30), PRODUCT_ID VARCHAR(30), ADDRESS_ID VARCHAR(30),PRIMARY KEY(ID), FOREIGN KEY(USER_ID) REFERENCES USERS(ID),FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESSES(ID));

SHOW TABLES;

DROP TABLE ORDERS;
DROP TABLE PRODUCT_IMAGES;
DROP TABLE CATEGORIES;
DROP TABLE PRODUCTS;

SHOW TABLES;

create table PRODUCTS (id varchar(30) NOT NULL, name VARCHAR(50) NOT NULL , QUANTITY INT(5) NOT NULL, PRIMARY KEY(id)) ;

create table PRODUCT_IMAGES ( PRODUCT_ID VARCHAR(30) NOT NULL , IMAGE TEXT NOT NULL , FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID));

create table CATEGORIES ( PRODUCT_ID VARCHAR(30) NOT NULL , CATEGORY VARCHAR(100) NOT NULL , FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID));

CREATE TABLE ORDERS ( ID VARCHAR(30) NOT NULL, USER_ID VARCHAR(30), PRODUCT_ID VARCHAR(30), ADDRESS_ID VARCHAR(30),PRIMARY KEY(ID), FOREIGN KEY(USER_ID) REFERENCES USERS(ID),FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESSES(ID));


SHOW TABLES;